const refs = {
  // main page

  menuBtn: document.querySelector('.burger-btn'),
  mobileMenu: document.querySelector('[data-menu]'),
  cartOverlay: document.querySelector('.cart-overlay'),
  featuresLeftList: document.querySelector('.left-list'),
  featuresRightList: document.querySelector('.right-list'),
  featuresCard: document.querySelector('.feature-section__main-card'),
  featureSection: document.querySelector('.feature-section__main-list'),
  arrivalList: document.querySelector('.arrival__list'),
  popularList: document.querySelector('.popular__list'),
  searchBackdrop: document.querySelector('.search-backdrop'),
  searchList: document.querySelector('.search-list'),
  mainSearchInput: document.querySelector('.main-search__input'),
  loader: document.querySelector('.loader'),
  footerInput: document.querySelector('.footer__input'),

  // checkout page

  cardForm: document.querySelector('.payment-card'),
  transferForm: document.querySelector('.payment-bank'),
  paypalForm: document.querySelector('.payment-paypal'),
  paymentMethodForm: document.querySelectorAll('.checkout-form__group'),
  buyerFormInput: document.querySelectorAll('.buyer-input'),
  submitBtn: document.querySelector('.checkout-form__submit-btn'),
  form: document.querySelector('.checkout-form'),
  cardInput: document.querySelectorAll('.card-input'),
  transferInput: document.querySelectorAll('.bank-input'),
  paypalInput: document.querySelectorAll('.paypal-input'),
  agreeCheckbox: document.querySelector('.agree-checkbox'),
  errors: document.querySelectorAll('.error'),
  radioBtnPaymentList: document.querySelectorAll('.radio-btn'),
  radioBtnBankList: document.querySelectorAll('.radio-bank-btn'),
  finalProductList: document.querySelector('.checkout__final-list'),
  totalCheckout: document.querySelector('.checkout__total-price'),
  creditInfo: document.querySelector('.checkout__credit-info'),
  creditCheckout: document.querySelector('.checkout__credit-price'),
  paymentCheckout: document.querySelector('.checkout__payment-price'),
  creditCheckoutBlock: document.querySelector('.checkout__credit-block'),
  paymentCheckoutBlock: document.querySelector('.checkout__payment-block'),
  map: document.querySelector('.map'),
  magazines: document.querySelector('.magazines-list'),
  deliveryForm: document.querySelector('.delivery__form'),
  postInput: document.getElementById('post-input'),
  postInputReset: document.querySelector('.post-input__reset'),
  magazineContainer: document.querySelector('.delivery-magazine__container'),
  postContainer: document.querySelector('.delivery-post__container'),
  dhlContainer: document.querySelector('.delivery-dhl__container'),
  deliveryInputs: document.querySelectorAll('.delivery__input'),
  magazineAddress: document.getElementById('magazine-street'),
  postName: document.getElementById('post-name'),
  postStreet: document.getElementById('street'),
  postCity: document.getElementById('city'),
  postRegion: document.getElementById('region'),
  postCode: document.getElementById('post-code'),
  postPhone: document.getElementById('post-phone'),
  postWeek: document.getElementById('week'),
  postSaturday: document.getElementById('saturday'),
  postSunday: document.getElementById('sunday'),
  dhlForm: document.querySelector('.delivery-dhl__form'),
  totalPriceInCheckoutPage: document.querySelector('.checkout__total-price'),
  creditDescription: document.querySelector('.checkout__credit-info'),
  dhlInputs: document.querySelectorAll('.delivery-dhl__input'),
  checkoutTolal: document.querySelector('.project-total'),

  // cart sidebar

  sidebarBtn: document.querySelector('.sidebar-btn'),
  sidebarCart: document.querySelector('.cart'),
  cartBtn: document.querySelector('.cart-btn'),
  loader: document.querySelector('.loader'),
  cartSidebarList: document.querySelector('.cart__list'),
  productsInCart: document.querySelector('.cart-item-count'),
  cartTotalPrice: document.querySelector('.cart__total'),
  productAmount: document.querySelector('.cart__product-count'),

  // products and categories pages

  productsList: document.querySelector('.products__list'),
  categoriesList: document.querySelector('.header__categories-list'),
  restCategories: document.querySelector('.rest-categories-list'),
  categoryTitle: document.querySelector('.category-title'),
  totalProductsInfo: document.querySelector('.total-products'),
  pagination: document.querySelector('.pagination-list'),
  searchFilter: document.querySelector('.search-input'),
  companiesFilter: document.querySelector('.companies-filter'),
  priceFilter: document.querySelector('.price-form'),
  priceInput: document.querySelectorAll('.price-input'),
  select: document.querySelector('.products__select'),
  selectForm: document.querySelector('.products__select-form'),
  searchCompanyInput: document.querySelector('.company__search-input'),

  // modal

  modalInput: document.querySelectorAll('.modal-input'),
  modalForm: document.querySelector('.modal-form'),
  modalSubmitBtn: document.querySelector('.modal-submit-btn'),
  modalCloseBtn: document.querySelector('.modal-btn'),
  modalOpenBtn: document.querySelector('.login-button'),
  modalBackdrop: document.querySelector('.backdrop'),
  iconCross: document.querySelector('.modal-cross')
  modal: document.querySelector('.modal'),
  checkoutModal: document.querySelector('.checkout-modal'),


  //product page

  productContainer: document.querySelector('.product'),
  productCount: document.querySelector('.product__total'),
  productQuantity: document.querySelector('.product__quantity'),
  reviewForm: document.querySelector('.review__form'),
  reviewFormButton: document.querySelector('.review__form-button'),
  reviewFormInputs: document.querySelectorAll('.review__form-input'),
  reviewList: document.querySelector('.review__list'),
  reviewField: document.querySelector('.review__field'),
  ratingList: document.querySelector('.product__rating-list'),
  ratingStars: document.querySelectorAll('.star'),
  sliderList: document.querySelector('.similar-slider'),
  latestList: document.querySelector('.latest-slider'),
  similarProductsBlock: document.querySelector('.similar-section'),
  textArea: document.querySelector('.textarea-input'),

  // Cart Page

  tableBody: document.querySelector('.table-body'),
  cartTotalPriceOnPage: document.querySelector('.cart__total-price'),
  couponForm: document.querySelector('.coupon-form'),
  couponButton: document.querySelector('.coupon-button'),
  alsoBuyList: document.querySelector('.also-buy__list'),
  creditButton: document.querySelector('.credit-button'),
  modalTotal: document.querySelectorAll('.modal-table__total'),
  creditPercent: document.querySelectorAll('.modal-table__credit-text'),
  priceForMonth: document.querySelectorAll('.modal-table__credit'),
  modalSelect: document.querySelectorAll('.modal-table__select'),
  creditModal: document.querySelector('.credit-modal'),
  bankInputs: document.querySelectorAll('.modal-table__radio'),
  creditPrice: document.querySelector('.credit-price'),
  paymentPrice: document.querySelector('.payment-price'),
  modalButton: document.querySelector('.modal-table__button'),
  creditPriceBlock: document.querySelector('.credit-block'),
  paymentPriceBlock: document.querySelector('.payment-block'),
};

export default refs;
