const refs = {
  menuBtn: document.querySelector('.burger-btn'),
  mobileMenu: document.querySelector('[data-menu]'),
  cardForm: document.querySelector('.payment-card'),
  transferForm: document.querySelector('.payment-bank'),
  paypalForm: document.querySelector('.payment-paypal'),
  paymentMethodForm: document.querySelectorAll('.checkout-form__group'),
  buyerFormInput: document.querySelectorAll('.buyer-input'),
  submitBtn: document.querySelector('.checkout-form__submit-btn'),
  form: document.querySelector('.checkout-form'),
  cardInput: document.querySelectorAll('.card-input'),
  transferInput: document.querySelectorAll('.bank-input'),
  paypalInput: document.querySelectorAll('.paypal-input'),
  agreeCheckbox: document.querySelector('.agree-checkbox'),
  errors: document.querySelectorAll('.error'),
  sidebarBtn: document.querySelector('.sidebar-btn'),
  cartOverlay: document.querySelector('.cart-overlay'),
  sidebarCart: document.querySelector('.cart'),
  cartBtn: document.querySelector('.cart-btn'),
  loader: document.querySelector('.loader'),
  cartItem: document.querySelector('.cart__item'),
  cartItemCount: document.querySelector('.cart-item-count'),
  cartTotal: document.querySelector('.cart__total'),
  featuresLeftList: document.querySelector('.left-list'),
  featuresRightList: document.querySelector('.right-list'),
  featuresCard: document.querySelector('.feature-section__main-card'),
  radioBtnPaymentList: document.querySelectorAll('.radio-btn'),
  radioBtnBankList: document.querySelectorAll('.radio-bank-btn'),
  featureSection: document.querySelector('.feature-section__main-list'),
  arrivalList: document.querySelector('.arrival__list'),
  popularList: document.querySelector('.popular__list'),
  productsList: document.querySelector('.products__list'),
  priceRange: document.querySelector('.progress'),
  priceFilter: document.querySelector('.price-filter'),
  range: document.querySelector('.range'),
  searchFilter: document.querySelector('.search-filter'),
  companiesFilter: document.querySelector('.companies-list'),
};

export default refs;
